# Nuovi esercizi: funzionali, catena posteriore, deltoidi posteriori e schiena, stretching, yoga.
# Idempotente: sostituisce le voci con lo stesso id. Uso: python3 scripts/catalogo_nuovi.py
import json

def E(id, nome, cat, attrezzatura, tipo, esecuzione, muscoli, schemi, attrezzi, livello, impatto=False, sollecita=(), funzionale=False):
    return dict(id=id, nome=nome, categoria=cat, attrezzatura=attrezzatura, tipoRegistrazione=tipo, esecuzione=esecuzione,
                sbloccabile=False, muscoli=muscoli, schemi=schemi, attrezzi=attrezzi, livello=livello, impatto=impatto,
                sollecita=list(sollecita), funzionale=funzionale)

NUOVI = [
 # ---------------- funzionali / multiarticolari ----------------
 E('goblet_squat', 'Goblet squat', 'forza', ['kettlebell o manubrio'], 'carico_ripetizioni',
   ['Kettlebell tenuto al petto con due mani, piedi poco più larghi delle spalle.',
    'Scendi tra le ginocchia con il busto alto fino a cosce parallele o più in basso.',
    'Risali spingendo con tutto il piede, espira in salita.'],
   {'quadricipiti': 3, 'grande-gluteo': 2, 'adduttori': 2, 'addome': 1, 'erettori-spinali': 1}, ['squat'], [['kettlebell', 'manubri']], 1, sollecita=['ginocchia'], funzionale=True),
 E('affondo_indietro', 'Affondo indietro', 'forza', ['corpo libero o manubri'], 'carico_ripetizioni',
   ['In piedi, piedi larghezza anche.',
    'Fai un passo lungo indietro e scendi finché il ginocchio posteriore sfiora il pavimento.',
    'Spingi con il tallone anteriore per tornare in piedi e alterna.'],
   {'quadricipiti': 3, 'grande-gluteo': 3, 'medio-gluteo': 2, 'adduttori': 1, 'addome': 1}, ['affondo'], [], 1, sollecita=['ginocchia'], funzionale=True),
 E('affondo_laterale', 'Affondo laterale', 'forza', ['corpo libero o kettlebell'], 'carico_ripetizioni',
   ['Piedi molto larghi, punte in avanti.',
    'Siediti su una gamba piegando il ginocchio, l\'altra resta tesa con il piede a terra.',
    'Spingi per tornare al centro e cambia lato.'],
   {'adduttori': 3, 'quadricipiti': 2, 'grande-gluteo': 2, 'medio-gluteo': 2}, ['affondo'], [], 1, funzionale=True),
 E('split_squat_bulgaro', 'Split squat bulgaro', 'forza', ['panca', 'manubri'], 'carico_ripetizioni',
   ['Collo del piede posteriore appoggiato sulla panca, piede anteriore circa un passo avanti.',
    'Scendi in verticale fino a coscia anteriore parallela, busto leggermente inclinato.',
    'Risali spingendo con il piede anteriore; completa le ripetizioni e cambia gamba.'],
   {'quadricipiti': 3, 'grande-gluteo': 3, 'medio-gluteo': 2, 'adduttori': 1, 'obliqui': 1}, ['affondo'], [['panca']], 2, sollecita=['ginocchia'], funzionale=True),
 E('stacco_monopodalico', 'Stacco su una gamba', 'forza', ['kettlebell o manubrio'], 'carico_ripetizioni',
   ['In piedi su una gamba, peso nella mano opposta, ginocchio d\'appoggio morbido.',
    'Porta il busto avanti e la gamba libera indietro in linea con la schiena.',
    'Torna in piedi contraendo il gluteo della gamba d\'appoggio.'],
   {'femorali': 3, 'grande-gluteo': 3, 'medio-gluteo': 2, 'erettori-spinali': 2, 'obliqui': 1, 'polpacci': 1}, ['hinge'], [['kettlebell', 'manubri']], 2, funzionale=True),
 E('stacco_kettlebell', 'Stacco con kettlebell', 'forza', ['kettlebell'], 'carico_ripetizioni',
   ['Kettlebell tra i piedi, piedi larghezza anche.',
    'Anche indietro, schiena neutra, afferra la maniglia con due mani.',
    'Spingi il pavimento ed estendi le anche fino in piedi; scendi con lo stesso percorso.'],
   {'grande-gluteo': 3, 'femorali': 2, 'quadricipiti': 2, 'erettori-spinali': 2, 'lombari': 2, 'avambraccio-flessori': 1}, ['hinge'], [['kettlebell']], 1, funzionale=True),
 E('kettlebell_clean', 'Clean con kettlebell', 'potenza', ['kettlebell'], 'carico_ripetizioni',
   ['Kettlebell davanti ai piedi, afferralo con una mano e portalo tra le gambe.',
    'Estendi le anche con forza e tieni il gomito vicino al fianco.',
    'Accogli il kettlebell in posizione di rack sull\'avambraccio, poi riportalo giù.'],
   {'grande-gluteo': 3, 'femorali': 2, 'trapezio-alto': 2, 'deltoide-anteriore': 2, 'avambraccio-flessori': 2, 'addome': 1}, ['hinge', 'balistico'], [['kettlebell']], 2, funzionale=True),
 E('thruster_manubri', 'Thruster con manubri', 'potenza', ['manubri'], 'carico_ripetizioni',
   ['Manubri alle spalle, piedi larghezza spalle.',
    'Scendi in squat completo mantenendo i gomiti alti.',
    'Risali con forza e usa la spinta per portare i manubri sopra la testa.'],
   {'quadricipiti': 3, 'deltoide-anteriore': 3, 'grande-gluteo': 2, 'tricipite': 2, 'addome': 1, 'trapezio-alto': 1}, ['squat', 'spinta-verticale'], [['manubri']], 2, sollecita=['spalle'], funzionale=True),
 E('wall_ball', 'Wall ball', 'potenza', ['palla medica'], 'ripetizioni',
   ['Palla al petto, a un passo dal muro.',
    'Scendi in squat e risali con forza lanciando la palla verso un punto alto del muro.',
    'Riprendi la palla e scendi subito nello squat successivo.'],
   {'quadricipiti': 3, 'grande-gluteo': 2, 'deltoide-anteriore': 3, 'tricipite': 2, 'addome': 1}, ['squat', 'spinta-verticale', 'balistico'], [['palla-medica']], 1, funzionale=True),
 E('slam_palla_medica', 'Slam con palla medica', 'potenza', ['palla medica'], 'ripetizioni',
   ['Palla sopra la testa a braccia tese, sulle punte.',
    'Scaglia la palla a terra davanti a te piegando anche e busto.',
    'Riprendi la palla con la schiena neutra e torna in posizione.'],
   {'gran-dorsale': 3, 'addome': 3, 'deltoide-anteriore': 2, 'grande-gluteo': 2, 'tricipite': 1}, ['balistico', 'hinge'], [['palla-medica']], 1, funzionale=True),
 E('burpee', 'Burpee', 'potenza', [], 'ripetizioni',
   ['In piedi, scendi in squat e appoggia le mani a terra.',
    'Porta i piedi indietro in plank e fai un piegamento.',
    'Riporta i piedi alle mani e salta in alto con le braccia sopra la testa.'],
   {'quadricipiti': 2, 'pettorali': 2, 'tricipite': 2, 'addome': 2, 'deltoide-anteriore': 2, 'polpacci': 1}, ['pliometria', 'locomozione', 'spinta-orizzontale'], [], 2, impatto=True, sollecita=['polsi', 'ginocchia'], funzionale=True),
 E('bear_crawl', 'Bear crawl', 'core', [], 'distanza',
   ['In quadrupedia con le ginocchia sollevate di pochi centimetri da terra.',
    'Avanza muovendo insieme mano e piede opposti a passi corti.',
    'Mantieni la schiena piatta e il bacino fermo per tutta la distanza.'],
   {'addome': 3, 'obliqui': 2, 'deltoide-anteriore': 2, 'quadricipiti': 2, 'tricipite': 1}, ['locomozione', 'anti-estensione', 'anti-rotazione'], [], 1, sollecita=['polsi'], funzionale=True),
 E('renegade_row', 'Renegade row', 'forza', ['manubri'], 'carico_ripetizioni',
   ['In plank sulle mani impugnando due manubri, piedi larghi.',
    'Tira un manubrio verso il fianco senza ruotare il bacino.',
    'Riappoggia e alterna il lato.'],
   {'gran-dorsale': 3, 'addome': 2, 'obliqui': 3, 'deltoide-posteriore': 2, 'bicipite': 1, 'tricipite': 1}, ['tirata-orizzontale', 'anti-rotazione'], [['manubri']], 2, sollecita=['polsi'], funzionale=True),
 E('overhead_carry', 'Overhead carry', 'forza', ['kettlebell o manubrio'], 'distanza',
   ['Peso sopra la testa a braccio teso, bicipite vicino all\'orecchio.',
    'Costole basse e addome contratto.',
    'Cammina a passi regolari per la distanza prevista e cambia braccio.'],
   {'deltoide-anteriore': 3, 'trapezio-alto': 2, 'trapezio-basso': 2, 'tricipite': 2, 'obliqui': 2, 'addome': 2}, ['trasporto', 'anti-flessione-laterale'], [['kettlebell', 'manubri']], 2, sollecita=['spalle'], funzionale=True),
 E('kettlebell_windmill', 'Windmill con kettlebell', 'core', ['kettlebell'], 'carico_ripetizioni',
   ['Kettlebell sopra la testa a braccio teso, piedi larghi e ruotati dal lato opposto.',
    'Spingi l\'anca verso il lato del peso e scendi con la mano libera lungo la gamba.',
    'Sguardo sul kettlebell; risali allo stesso modo.'],
   {'obliqui': 3, 'deltoide-anteriore': 2, 'medio-gluteo': 2, 'femorali': 2, 'trapezio-basso': 1}, ['anti-flessione-laterale', 'mobilita'], [['kettlebell']], 3, sollecita=['spalle'], funzionale=True),
 E('chop_mezzo_ginocchio', 'Chop in mezzo ginocchio', 'core', ['elastico o cavo'], 'ripetizioni',
   ['In mezzo ginocchio di fianco all\'ancoraggio alto, mani sulla maniglia.',
    'Tira in diagonale verso l\'anca opposta ruotando il busto.',
    'Torna lentamente senza muovere il bacino; completa e cambia lato.'],
   {'obliqui': 3, 'addome': 2, 'gran-dorsale': 1, 'deltoide-anteriore': 1, 'grande-gluteo': 1}, ['rotazione', 'anti-rotazione'], [['elastico', 'cavo']], 1, funzionale=True),
 E('ab_rollout', 'Rollout', 'core', ['ruota o slider'], 'ripetizioni',
   ['In ginocchio, mani sulla ruota o sugli slider sotto le spalle.',
    'Allunga le braccia in avanti mantenendo il bacino in linea.',
    'Torna indietro contraendo l\'addome, espira in rientro.'],
   {'addome': 3, 'obliqui': 2, 'gran-dorsale': 2, 'deltoide-anteriore': 1}, ['anti-estensione'], [['slider']], 2, sollecita=['schiena'], funzionale=False),
 E('plank_shoulder_tap', 'Plank con tocco spalla', 'core', [], 'ripetizioni',
   ['In plank sulle mani, piedi larghi.',
    'Solleva una mano e tocca la spalla opposta senza far ruotare il bacino.',
    'Riappoggia e alterna con un ritmo regolare.'],
   {'addome': 3, 'obliqui': 3, 'deltoide-anteriore': 2, 'pettorali': 1, 'tricipite': 1}, ['anti-rotazione', 'anti-estensione'], [], 1, sollecita=['polsi'], funzionale=True),
 E('hanging_knee_raise', 'Ginocchia al petto alla sbarra', 'core', ['sbarra'], 'ripetizioni',
   ['Appeso alla sbarra, scapole attive e gambe unite.',
    'Porta le ginocchia verso il petto arrotondando il bacino.',
    'Scendi lentamente senza oscillare.'],
   {'addome': 3, 'obliqui': 2, 'avambraccio-flessori': 2, 'gran-dorsale': 1, 'retto-femorale': 2}, ['anti-estensione'], [['sbarra']], 2, funzionale=False),
 E('box_jump', 'Salto sul box', 'potenza', ['box'], 'ripetizioni',
   ['In piedi davanti al box, piedi larghezza anche.',
    'Carica piegando anche e ginocchia e slancia le braccia.',
    'Salta e atterra morbido al centro del box; scendi camminando.'],
   {'quadricipiti': 3, 'grande-gluteo': 3, 'polpacci': 2, 'femorali': 1}, ['pliometria'], [['box']], 2, impatto=True, sollecita=['ginocchia'], funzionale=True),
 # ---------------- lombari e catena posteriore ----------------
 E('back_extension', 'Iperestensioni', 'forza', ['panca per iperestensioni'], 'ripetizioni',
   ['Anche appoggiate al cuscino, talloni bloccati, braccia incrociate al petto.',
    'Scendi piegando le anche con la schiena neutra.',
    'Risali fino ad allineare busto e gambe contraendo glutei e lombari.'],
   {'erettori-spinali': 3, 'lombari': 3, 'grande-gluteo': 2, 'femorali': 2}, ['hinge'], [['panca-iperestensioni']], 1, funzionale=False),
 E('superman', 'Superman', 'core', [], 'tempo',
   ['Prono, braccia tese oltre la testa.',
    'Solleva insieme braccia, petto e gambe di pochi centimetri.',
    'Mantieni guardando il pavimento e respira regolarmente.'],
   {'erettori-spinali': 3, 'lombari': 3, 'grande-gluteo': 2, 'trapezio-basso': 1, 'deltoide-posteriore': 1}, ['anti-estensione'], [['tappetino']], 1, funzionale=False),
 E('good_morning', 'Good morning', 'forza', ['bilanciere'], 'carico_ripetizioni',
   ['Bilanciere sulle spalle, piedi larghezza anche, ginocchia morbide.',
    'Porta le anche indietro e inclina il busto con la schiena neutra.',
    'Risali spingendo le anche in avanti.'],
   {'femorali': 3, 'erettori-spinali': 3, 'lombari': 2, 'grande-gluteo': 2}, ['hinge'], [['bilanciere']], 2, sollecita=['schiena'], funzionale=True),
 E('ponte_glutei', 'Ponte glutei', 'forza', [], 'ripetizioni',
   ['Supino, ginocchia piegate, piedi a terra vicino ai glutei.',
    'Spingi i talloni e solleva il bacino fino ad allineare spalle, anche e ginocchia.',
    'Tieni un secondo contraendo i glutei e scendi.'],
   {'grande-gluteo': 3, 'femorali': 2, 'lombari': 1, 'medio-gluteo': 1}, ['hinge'], [['tappetino']], 1, funzionale=False),
 E('ponte_monopodalico', 'Ponte su una gamba', 'forza', [], 'ripetizioni',
   ['Supino, un piede a terra e l\'altra gamba tesa verso il soffitto.',
    'Solleva il bacino spingendo con il tallone a terra.',
    'Mantieni il bacino orizzontale, scendi e completa prima di cambiare lato.'],
   {'grande-gluteo': 3, 'medio-gluteo': 2, 'femorali': 2, 'obliqui': 1}, ['hinge'], [['tappetino']], 2, funzionale=True),
 # ---------------- deltoidi posteriori e schiena ----------------
 E('alzate_posteriori', 'Alzate posteriori', 'forza', ['manubri'], 'carico_ripetizioni',
   ['Busto inclinato in avanti con la schiena neutra, manubri sotto le spalle.',
    'Apri le braccia di lato con i gomiti leggermente piegati.',
    'Arriva all\'altezza delle spalle e scendi lentamente.'],
   {'deltoide-posteriore': 3, 'trapezio-medio': 2, 'trapezio-basso': 1, 'erettori-spinali': 1}, ['tirata-orizzontale', 'scapole'], [['manubri']], 1),
 E('band_pull_apart', 'Band pull apart', 'forza', ['elastico'], 'ripetizioni',
   ['In piedi, elastico teso davanti al petto a braccia tese.',
    'Apri le braccia avvicinando le scapole fino a toccare il petto con l\'elastico.',
    'Torna controllato.'],
   {'deltoide-posteriore': 3, 'trapezio-medio': 3, 'trapezio-basso': 1}, ['tirata-orizzontale', 'scapole'], [['elastico']], 1),
 E('ytw_prono', 'Y-T-W da prono', 'forza', ['corpo libero o manubri leggeri'], 'ripetizioni',
   ['Prono a terra o su panca inclinata, fronte bassa.',
    'Solleva le braccia disegnando in sequenza una Y, una T e una W.',
    'Tieni un secondo in ogni posizione avvicinando le scapole.'],
   {'trapezio-basso': 3, 'trapezio-medio': 3, 'deltoide-posteriore': 2, 'erettori-spinali': 1}, ['scapole'], [['tappetino']], 1),
 E('lat_machine', 'Lat machine', 'forza', ['cavo'], 'carico_ripetizioni',
   ['Seduto con le cosce bloccate, presa più larga delle spalle.',
    'Abbassa le scapole e tira la barra verso la parte alta del petto.',
    'Risali controllato fino a braccia tese.'],
   {'gran-dorsale': 3, 'bicipite': 2, 'trapezio-basso': 2, 'deltoide-posteriore': 1, 'avambraccio-flessori': 1}, ['tirata-verticale'], [['cavo']], 1),
 E('rematore_cavo', 'Rematore al cavo', 'forza', ['cavo'], 'carico_ripetizioni',
   ['Seduto, piedi sulla pedana, busto eretto e maniglia a braccia tese.',
    'Tira la maniglia verso l\'ombelico portando i gomiti indietro.',
    'Torna allungando le braccia senza inclinare il busto.'],
   {'gran-dorsale': 3, 'trapezio-medio': 3, 'deltoide-posteriore': 2, 'bicipite': 2, 'erettori-spinali': 1}, ['tirata-orizzontale'], [['cavo']], 1),
 E('rematore_bilanciere', 'Rematore con bilanciere', 'forza', ['bilanciere'], 'carico_ripetizioni',
   ['Busto inclinato a circa 45 gradi, schiena neutra, bilanciere a braccia tese.',
    'Tira il bilanciere verso l\'ombelico portando i gomiti indietro.',
    'Scendi controllato mantenendo l\'inclinazione del busto.'],
   {'gran-dorsale': 3, 'trapezio-medio': 3, 'deltoide-posteriore': 2, 'bicipite': 2, 'erettori-spinali': 2, 'lombari': 2}, ['tirata-orizzontale', 'hinge'], [['bilanciere']], 2, sollecita=['schiena'], funzionale=True),
 E('rematore_panca_inclinata', 'Rematore su panca inclinata', 'forza', ['panca', 'manubri'], 'carico_ripetizioni',
   ['Prono sulla panca inclinata, petto appoggiato, manubri a braccia tese.',
    'Tira i manubri verso le anche avvicinando le scapole.',
    'Scendi fino a braccia tese.'],
   {'gran-dorsale': 3, 'trapezio-medio': 3, 'deltoide-posteriore': 2, 'bicipite': 2}, ['tirata-orizzontale'], [['panca'], ['manubri']], 1),
 E('pulldown_braccia_tese', 'Pulldown a braccia tese', 'forza', ['cavo o elastico'], 'carico_ripetizioni',
   ['In piedi davanti all\'ancoraggio alto, braccia tese avanti, busto leggermente inclinato.',
    'Porta le mani verso le cosce a braccia tese contraendo i dorsali.',
    'Torna lentamente fino all\'altezza degli occhi.'],
   {'gran-dorsale': 3, 'trapezio-basso': 2, 'tricipite': 1, 'addome': 1}, ['tirata-verticale'], [['cavo', 'elastico']], 1),
 # ---------------- stretching ----------------
 E('stretch_femorali', 'Stretching femorali', 'stretching', ['elastico o asciugamano'], 'tempo',
   ['Supino, elastico sotto la pianta di un piede.',
    'Porta la gamba tesa verso l\'alto finché senti tensione dietro la coscia.',
    'Mantieni respirando lentamente, poi cambia gamba.'],
   {'femorali': 3, 'polpacci': 1}, ['stretching'], [['tappetino']], 1),
 E('stretch_quadricipite', 'Stretching quadricipite', 'stretching', [], 'tempo',
   ['In piedi, una mano al muro.',
    'Afferra la caviglia e porta il tallone verso il gluteo con le ginocchia vicine.',
    'Spingi leggermente l\'anca avanti e mantieni; cambia gamba.'],
   {'quadricipiti': 3}, ['stretching'], [], 1),
 E('stretch_flessori_anca', 'Stretching flessori dell\'anca', 'stretching', [], 'tempo',
   ['In mezzo ginocchio, ginocchio posteriore sul tappetino.',
    'Contrai il gluteo posteriore e porta il bacino in avanti.',
    'Mantieni con il busto eretto e cambia lato.'],
   {'retto-femorale': 3, 'addome': 1}, ['stretching'], [['tappetino']], 1),
 E('stretch_piriforme', 'Stretching piriforme', 'stretching', [], 'tempo',
   ['Supino, caviglia appoggiata sul ginocchio opposto.',
    'Afferra la coscia della gamba d\'appoggio e portala verso il petto.',
    'Mantieni con le spalle rilassate e cambia lato.'],
   {'grande-gluteo': 3, 'medio-gluteo': 3}, ['stretching'], [['tappetino']], 1),
 E('stretch_pettorale', 'Stretching pettorale al muro', 'stretching', [], 'tempo',
   ['Di fianco al muro, avambraccio appoggiato con il gomito all\'altezza della spalla.',
    'Ruota lentamente il busto dal lato opposto.',
    'Mantieni respirando e cambia lato.'],
   {'pettorali': 3, 'deltoide-anteriore': 2}, ['stretching'], [], 1),
 E('stretch_polpacci', 'Stretching polpacci al muro', 'stretching', [], 'tempo',
   ['Mani al muro, una gamba avanti piegata e una dietro tesa.',
    'Tallone posteriore a terra, porta il bacino verso il muro.',
    'Mantieni e cambia gamba.'],
   {'gastrocnemio': 3, 'soleo': 2}, ['stretching'], [], 1),
 E('stretch_spalla', 'Stretching spalla a braccio incrociato', 'stretching', [], 'tempo',
   ['In piedi, porta un braccio teso davanti al petto.',
    'Con l\'altra mano spingi il braccio verso il corpo sopra il gomito.',
    'Spalle basse, mantieni e cambia braccio.'],
   {'deltoide-posteriore': 3, 'trapezio-medio': 1}, ['stretching'], [], 1),
 E('stretch_adduttori', 'Stretching adduttori a farfalla', 'stretching', [], 'tempo',
   ['Seduto, piante dei piedi unite e ginocchia aperte.',
    'Busto eretto, mani sui piedi.',
    'Lascia scendere le ginocchia e inclinati in avanti espirando.'],
   {'adduttori': 3, 'lombari': 1}, ['stretching'], [['tappetino']], 1),
 E('stretch_laterale', 'Allungamento laterale in piedi', 'stretching', [], 'tempo',
   ['In piedi, piedi uniti, un braccio sopra la testa.',
    'Inclina il busto dal lato opposto allungando il fianco.',
    'Mantieni respirando nel fianco allungato e cambia lato.'],
   {'gran-dorsale': 3, 'obliqui': 2}, ['stretching'], [], 1),
 # ---------------- yoga ----------------
 E('cane_testa_giu', 'Cane a testa in giù', 'yoga', ['tappetino'], 'tempo',
   ['Da quadrupedia, solleva le anche portando il corpo a V rovesciata.',
    'Spingi il pavimento con le mani, talloni verso terra, testa tra le braccia.',
    'Respira lentamente dal naso mantenendo la posizione.'],
   {'femorali': 3, 'polpacci': 3, 'gran-dorsale': 2, 'deltoide-anteriore': 2, 'erettori-spinali': 1}, ['yoga'], [['tappetino']], 1, sollecita=['polsi']),
 E('posizione_bambino', 'Posizione del bambino', 'yoga', ['tappetino'], 'tempo',
   ['In ginocchio, alluci uniti e ginocchia leggermente aperte.',
    'Siediti sui talloni e porta la fronte a terra con le braccia avanti.',
    'Respira allargando la schiena a ogni inspirazione.'],
   {'erettori-spinali': 2, 'lombari': 3, 'gran-dorsale': 2, 'grande-gluteo': 1}, ['yoga'], [['tappetino']], 1),
 E('cobra', 'Cobra', 'yoga', ['tappetino'], 'tempo',
   ['Prono, mani a terra sotto le spalle, gomiti vicini al corpo.',
    'Inspirando, solleva il petto spingendo con le mani e allungando la colonna.',
    'Spalle lontane dalle orecchie; mantieni e scendi espirando.'],
   {'retto-addominale': 2, 'erettori-spinali': 2, 'pettorali': 1, 'retto-femorale': 1}, ['yoga'], [['tappetino']], 1),
 E('guerriero_1', 'Guerriero I', 'yoga', ['tappetino'], 'tempo',
   ['Piede anteriore avanti, piede posteriore ruotato di 45 gradi.',
    'Piega il ginocchio anteriore sopra la caviglia e porta le braccia sopra la testa.',
    'Bacino verso avanti, respira e mantieni; cambia lato.'],
   {'quadricipiti': 2, 'grande-gluteo': 2, 'retto-femorale': 2, 'deltoide-anteriore': 1, 'addome': 1}, ['yoga'], [['tappetino']], 1, funzionale=True),
 E('guerriero_2', 'Guerriero II', 'yoga', ['tappetino'], 'tempo',
   ['Piedi larghi, piede anteriore avanti e piede posteriore parallelo al bordo del tappetino.',
    'Piega il ginocchio anteriore sopra la caviglia e apri le braccia all\'altezza delle spalle.',
    'Sguardo oltre la mano anteriore, mantieni e cambia lato.'],
   {'quadricipiti': 2, 'adduttori': 2, 'medio-gluteo': 2, 'deltoide-anteriore': 1, 'deltoide-posteriore': 1}, ['yoga'], [['tappetino']], 1, funzionale=True),
 E('triangolo', 'Triangolo', 'yoga', ['tappetino'], 'tempo',
   ['Piedi larghi, gambe tese, piede anteriore ruotato verso il fondo del tappetino.',
    'Allunga il busto sopra la gamba anteriore e appoggia la mano sulla tibia.',
    'Braccio superiore verso il soffitto, torace aperto; mantieni e cambia lato.'],
   {'femorali': 2, 'obliqui': 2, 'adduttori': 2, 'medio-gluteo': 1}, ['yoga'], [['tappetino']], 1),
 E('piccione', 'Piccione', 'yoga', ['tappetino'], 'tempo',
   ['Da quadrupedia porta un ginocchio avanti dietro il polso, tibia di traverso.',
    'Allunga l\'altra gamba indietro con il collo del piede a terra.',
    'Scendi con il busto in avanti respirando lentamente; cambia lato.'],
   {'grande-gluteo': 3, 'medio-gluteo': 3, 'retto-femorale': 2}, ['yoga'], [['tappetino']], 2, sollecita=['ginocchia']),
 E('albero', 'Albero', 'yoga', ['tappetino'], 'tempo',
   ['In piedi su una gamba, pianta dell\'altro piede sull\'interno della coscia o del polpaccio.',
    'Mani unite al petto, poi sopra la testa.',
    'Sguardo su un punto fisso, respira e mantieni; cambia lato.'],
   {'medio-gluteo': 2, 'polpacci': 2, 'tibiale-anteriore': 2, 'addome': 1, 'adduttori': 1}, ['yoga'], [], 1, funzionale=True),
 E('affondo_basso', 'Affondo basso', 'yoga', ['tappetino'], 'tempo',
   ['Piede anteriore avanti, ginocchio posteriore a terra.',
    'Porta il bacino in avanti e in basso, braccia sopra la testa.',
    'Allunga la colonna respirando; cambia lato.'],
   {'retto-femorale': 3, 'quadricipiti': 1, 'grande-gluteo': 1, 'addome': 1}, ['yoga'], [['tappetino']], 1),
 E('torsione_supina', 'Torsione supina', 'yoga', ['tappetino'], 'tempo',
   ['Supino, ginocchia piegate, braccia aperte a T.',
    'Lascia cadere le ginocchia da un lato mantenendo le spalle a terra.',
    'Sguardo dal lato opposto, respira e cambia lato.'],
   {'obliqui': 3, 'lombari': 2, 'grande-gluteo': 1}, ['yoga'], [['tappetino']], 1),
 E('saluto_al_sole', 'Saluto al sole', 'yoga', ['tappetino'], 'ripetizioni',
   ['In piedi, inspira portando le braccia sopra la testa.',
    'Espira piegandoti in avanti, poi passa per plank e cobra fino al cane a testa in giù.',
    'Torna in piedi con la sequenza inversa, un movimento per ogni respiro.'],
   {'femorali': 2, 'erettori-spinali': 2, 'deltoide-anteriore': 2, 'pettorali': 1, 'tricipite': 1, 'addome': 1, 'polpacci': 1}, ['yoga'], [['tappetino']], 1, sollecita=['polsi'], funzionale=True),
]

p = 'src/data/exercises.json'
ex = json.load(open(p))
nuovi_id = {e['id'] for e in NUOVI}
ex = [e for e in ex if e['id'] not in nuovi_id] + NUOVI
json.dump(ex, open(p, 'w'), ensure_ascii=False, indent=2)
print('totale', len(ex), 'nuovi', len(NUOVI))
