# Esercizi aggiunti: addominali e core, piegamenti, cardio alle macchine, braccia e polpacci, ginocchio e caviglia.
# Idempotente: sostituisce le voci con lo stesso id. Uso: python3 scripts/catalogo_aggiunte.py
import json

def E(id, nome, cat, attrezzatura, tipo, esecuzione, muscoli, schemi, attrezzi, livello, impatto=False, sollecita=(), funzionale=False):
    return dict(id=id, nome=nome, categoria=cat, attrezzatura=attrezzatura, tipoRegistrazione=tipo, esecuzione=esecuzione,
                sbloccabile=False, muscoli=muscoli, schemi=schemi, attrezzi=attrezzi, livello=livello, impatto=impatto,
                sollecita=list(sollecita), funzionale=funzionale)

NUOVI = [
 # ---------------- addominali: flessione ----------------
 E('crunch_alzata', 'Crunch con alzata', 'core', ['manubrio, disco o palla medica'], 'carico_ripetizioni',
   ['Supino, ginocchia piegate e piedi a terra, peso tenuto al petto con due mani.',
    'Sali con il busto fino a 90 gradi, poi spingi il peso sopra la testa a braccia tese.',
    'Riporta il peso al petto e scendi lentamente, vertebra dopo vertebra.'],
   {'addome': 3, 'deltoide-anteriore': 2, 'tricipite': 1, 'obliqui': 1, 'retto-femorale': 1}, ['isolamento'], [['manubri', 'kettlebell', 'palla-medica'], ['tappetino']], 1),
 E('crunch_inverso', 'Crunch inverso', 'core', ['tappetino'], 'ripetizioni',
   ['Supino, braccia lungo i fianchi, anche e ginocchia piegate a 90 gradi.',
    'Espira e porta le ginocchia verso il petto staccando il bacino da terra.',
    'Riappoggia il bacino lentamente senza far cadere le gambe.'],
   {'addome': 3, 'obliqui': 1, 'retto-femorale': 1}, ['isolamento'], [['tappetino']], 1),
 E('toes_to_bar', 'Crunch inverso alla sbarra (toes to bar)', 'core', ['sbarra'], 'ripetizioni',
   ['Appeso alla sbarra, braccia tese e scapole attive.',
    'Porta le gambe tese verso la sbarra arrotolando il bacino; all\'inizio fermati all\'altezza delle anche.',
    'Scendi controllando senza oscillare.'],
   {'addome': 3, 'retto-femorale': 2, 'gran-dorsale': 2, 'obliqui': 2, 'avambraccio-flessori': 1}, ['anti-estensione'], [['sbarra']], 3, sollecita=['spalle']),
 E('v_up', 'V-up (libretto)', 'core', ['tappetino'], 'ripetizioni',
   ['Supino, gambe tese e braccia distese sopra la testa.',
    'Solleva insieme busto e gambe tese e porta le mani verso i piedi.',
    'Torna giù lentamente senza appoggiare del tutto spalle e talloni.'],
   {'addome': 3, 'retto-femorale': 2, 'obliqui': 1}, ['isolamento'], [['tappetino']], 2),
 E('crunch_cavo', 'Crunch al cavo in ginocchio', 'core', ['cavo con corda'], 'carico_ripetizioni',
   ['In ginocchio davanti al cavo alto, corda tenuta ai lati della testa.',
    'Fletti il busto portando i gomiti verso le cosce, bacino fermo.',
    'Risali lentamente fino a busto quasi verticale.'],
   {'addome': 3, 'obliqui': 2}, ['isolamento'], [['cavo']], 1),
 E('hollow_rock', 'Hollow rock', 'core', ['tappetino'], 'ripetizioni',
   ['In posizione hollow: zona lombare a terra, braccia e gambe tese e sollevate.',
    'Dondola avanti e indietro mantenendo la forma a barchetta.',
    'Il movimento parte dall\'addome, braccia e gambe restano ferme.'],
   {'addome': 3, 'retto-femorale': 1, 'obliqui': 1}, ['anti-estensione'], [['tappetino']], 2),

 # ---------------- rotazione e obliqui ----------------
 E('russian_twist', 'Russian twist', 'core', ['palla medica o disco'], 'carico_ripetizioni',
   ['Seduto, ginocchia piegate, busto inclinato indietro con la schiena dritta.',
    'Tieni il peso davanti al petto e ruota il busto portandolo accanto al fianco.',
    'Passa dall\'altro lato; per aumentare la difficoltà solleva i piedi.'],
   {'obliqui': 3, 'addome': 2, 'retto-femorale': 1}, ['rotazione'], [['palla-medica', 'manubri', 'kettlebell'], ['tappetino']], 1),
 E('bicicletta', 'Crunch a bicicletta', 'core', ['tappetino'], 'ripetizioni',
   ['Supino, mani dietro la testa, spalle sollevate.',
    'Porta un ginocchio verso il petto e ruota il busto verso di lui con il gomito opposto.',
    'Distendi la gamba e alterna in modo continuo.'],
   {'obliqui': 3, 'addome': 2, 'retto-femorale': 1}, ['rotazione'], [['tappetino']], 1),
 E('cross_crunch', 'Crunch laterale sul fianco', 'core', ['tappetino'], 'ripetizioni',
   ['Sdraiato su un fianco, gambe leggermente piegate, mano superiore dietro la testa.',
    'Solleva busto e gambe insieme avvicinando il gomito all\'anca.',
    'Scendi lentamente; completa le ripetizioni e cambia lato.'],
   {'obliqui': 3, 'addome': 1, 'medio-gluteo': 1}, ['isolamento'], [['tappetino']], 1),
 E('twist_cavo', 'Rotazione al cavo a braccia tese', 'core', ['cavo o elastico'], 'carico_ripetizioni',
   ['In piedi di fianco al cavo all\'altezza del petto, maniglia a braccia tese davanti allo sterno.',
    'Ruota il busto allontanandoti dal cavo, le braccia seguono il petto.',
    'Torna lentamente; completa le ripetizioni e cambia lato.'],
   {'obliqui': 3, 'addome': 2, 'deltoide-anteriore': 1, 'medio-gluteo': 1}, ['rotazione'], [['cavo', 'elastico']], 1, funzionale=True),

 # ---------------- anti-movimento ----------------
 E('stir_the_pot', 'Stir the pot su fitball', 'core', ['fitball'], 'ripetizioni',
   ['Plank con gli avambracci sulla fitball e i piedi larghi.',
    'Disegna piccoli cerchi con gli avambracci senza muovere il bacino.',
    'Fai le ripetizioni in un verso, poi nell\'altro.'],
   {'addome': 3, 'obliqui': 3, 'deltoide-anteriore': 1, 'grande-gluteo': 1}, ['anti-estensione', 'anti-rotazione'], [['fitball']], 2),
 E('plank_archer', 'Plank archer alternato', 'core', ['tappetino'], 'ripetizioni',
   ['Plank sulle mani con i piedi larghi.',
    'Sposta il peso su una mano e allunga l\'altro braccio di lato, teso.',
    'Torna al centro e alterna senza ruotare il bacino.'],
   {'addome': 3, 'obliqui': 2, 'deltoide-anteriore': 2, 'pettorali': 1, 'tricipite': 1}, ['anti-rotazione'], [['tappetino']], 2, sollecita=['polsi']),
 E('body_saw', 'Body saw', 'core', ['fitball o slider'], 'ripetizioni',
   ['Plank sugli avambracci, piedi sulla fitball o sugli slider.',
    'Spingi il corpo indietro allontanando i gomiti dalle spalle.',
    'Torna avanti mantenendo il bacino in linea con il busto.'],
   {'addome': 3, 'deltoide-anteriore': 2, 'gran-dorsale': 1, 'obliqui': 1}, ['anti-estensione'], [['fitball', 'slider']], 2),
 E('plank_pull_through', 'Plank con trascinamento del manubrio', 'core', ['manubrio o kettlebell'], 'ripetizioni',
   ['Plank sulle mani, manubrio a terra di fianco al busto.',
    'Con la mano opposta afferra il manubrio e trascinalo sotto il corpo fino all\'altro lato.',
    'Alterna le mani tenendo il bacino fermo.'],
   {'addome': 3, 'obliqui': 3, 'deltoide-anteriore': 1, 'gran-dorsale': 1}, ['anti-rotazione'], [['manubri', 'kettlebell']], 2, sollecita=['polsi']),

 # ---------------- dinamici ----------------
 E('mountain_climber', 'Mountain climbers', 'core', [], 'tempo',
   ['Plank sulle mani, spalle sopra i polsi.',
    'Porta un ginocchio verso il petto e torna indietro alternando le gambe in rapida successione.',
    'Bacino basso e fermo, respira in modo regolare.'],
   {'addome': 2, 'retto-femorale': 2, 'deltoide-anteriore': 2, 'quadricipiti': 1, 'obliqui': 1}, ['anti-estensione', 'cardio'], [], 1, sollecita=['polsi']),
 E('plank_jack', 'Plank jack', 'core', [], 'tempo',
   ['Plank sulle mani, piedi uniti.',
    'Con un piccolo salto apri i piedi e poi richiudili.',
    'Il bacino resta alla stessa altezza.'],
   {'addome': 2, 'medio-gluteo': 2, 'adduttori': 2, 'deltoide-anteriore': 1}, ['anti-estensione', 'cardio'], [], 1, sollecita=['polsi']),
 E('flutter_kick', 'Gambe alternate da supino (flutter kick)', 'core', ['tappetino'], 'tempo',
   ['Supino, mani sotto i glutei, zona lombare a terra.',
    'Solleva le gambe tese di pochi centimetri.',
    'Alza e abbassa le gambe in modo alternato con movimenti piccoli e rapidi.'],
   {'addome': 3, 'retto-femorale': 2}, ['anti-estensione'], [['tappetino']], 1),

 # ---------------- cardio alle macchine ----------------
 E('tapis_roulant', 'Corsa sul tapis roulant', 'cardio', ['tapis roulant'], 'tempo',
   ['Imposta velocità e pendenza prima di salire, poi parti camminando.',
    'Corri al centro del nastro con passi corti e busto leggermente inclinato in avanti.',
    'Mantieni il ritmo previsto; rallenta camminando prima di scendere.'],
   {'quadricipiti': 2, 'femorali': 2, 'polpacci': 2, 'grande-gluteo': 2}, ['cardio'], [['macchine-cardio']], 1, impatto=True, sollecita=['ginocchia']),
 E('cyclette', 'Cyclette', 'cardio', ['cyclette'], 'tempo',
   ['Sella all\'altezza dell\'anca: con il pedale in basso il ginocchio resta appena piegato.',
    'Pedala con ritmo costante spingendo con tutta la pianta.',
    'Busto fermo e spalle rilassate.'],
   {'quadricipiti': 3, 'grande-gluteo': 2, 'femorali': 1, 'polpacci': 1}, ['cardio'], [['macchine-cardio']], 1),
 E('air_bike', 'Air bike', 'cardio', ['air bike'], 'tempo',
   ['Seduto, mani sulle maniglie mobili, piedi sui pedali.',
    'Spingi e tira con le braccia mentre pedali, in modo coordinato.',
    'Più forte spingi, più aumenta la resistenza.'],
   {'quadricipiti': 2, 'grande-gluteo': 2, 'deltoide-anteriore': 2, 'gran-dorsale': 2, 'pettorali': 1, 'tricipite': 1, 'bicipite': 1}, ['cardio'], [['macchine-cardio']], 1, funzionale=True),
 E('vogatore', 'Vogatore', 'cardio', ['vogatore'], 'tempo',
   ['Seduto, piedi fissati, braccia tese sulla maniglia e tibie verticali.',
    'Spingi con le gambe, poi porta indietro il busto e tira la maniglia sotto il petto.',
    'Torna con l\'ordine inverso: braccia, busto, gambe.'],
   {'gran-dorsale': 3, 'quadricipiti': 2, 'grande-gluteo': 2, 'trapezio-medio': 2, 'deltoide-posteriore': 2, 'femorali': 1, 'bicipite': 1, 'erettori-spinali': 1}, ['cardio'], [['macchine-cardio']], 1, funzionale=True),

 # ---------------- tirate ----------------
 E('lat_machine_inversa', 'Lat machine presa inversa stretta', 'forza', ['cavo'], 'carico_ripetizioni',
   ['Seduto, presa supina con le mani alla larghezza delle spalle o più strette.',
    'Tira la barra verso la parte alta del petto portando i gomiti in basso e vicino ai fianchi.',
    'Risali lentamente fino a braccia tese.'],
   {'gran-dorsale': 3, 'bicipite': 3, 'trapezio-basso': 1, 'avambraccio-flessori': 1}, ['tirata-verticale'], [['cavo']], 1),
 E('pulley_alto', 'Pulley alto (rematore al cavo alto)', 'forza', ['cavo'], 'carico_ripetizioni',
   ['Seduto davanti al cavo alto, braccia tese in avanti e in alto.',
    'Tira la maniglia verso il petto in diagonale, gomiti verso il basso e indietro.',
    'Stringi le scapole un istante e torna lentamente.'],
   {'gran-dorsale': 3, 'trapezio-medio': 2, 'trapezio-basso': 2, 'deltoide-posteriore': 2, 'bicipite': 2}, ['tirata-orizzontale', 'tirata-verticale'], [['cavo']], 1),
 E('rematore_alto', 'Rematore alto (tirata al mento)', 'forza', ['bilanciere, manubri o cavo'], 'carico_ripetizioni',
   ['In piedi, presa poco più larga delle spalle, peso davanti alle cosce.',
    'Solleva il peso lungo il corpo guidando con i gomiti fino all\'altezza del petto.',
    'Scendi lentamente; i gomiti restano più alti delle mani.'],
   {'trapezio-alto': 3, 'deltoide-anteriore': 2, 'deltoide-posteriore': 1, 'bicipite': 1, 'avambraccio-flessori': 1}, ['isolamento'], [['bilanciere', 'manubri', 'cavo']], 2, sollecita=['spalle']),
 E('rematore_isometrico', 'Rematore in isometria', 'forza', ['manubri o kettlebell'], 'tempo',
   ['Busto inclinato in avanti con la schiena neutra, ginocchia morbide.',
    'Tira i manubri fino ai fianchi e stringi le scapole.',
    'Mantieni la posizione respirando senza far scendere i gomiti.'],
   {'gran-dorsale': 3, 'trapezio-medio': 3, 'deltoide-posteriore': 2, 'bicipite': 2, 'erettori-spinali': 1}, ['tirata-orizzontale'], [['manubri', 'kettlebell']], 1),

 # ---------------- gambe ----------------
 E('squat_sumo', 'Squat sumo', 'forza', ['kettlebell o manubrio'], 'carico_ripetizioni',
   ['Piedi molto larghi, punte ruotate verso l\'esterno, peso tenuto tra le gambe a braccia tese.',
    'Scendi spingendo le ginocchia nella direzione delle punte, busto alto.',
    'Risali contraendo glutei e interno coscia.'],
   {'adduttori': 3, 'grande-gluteo': 3, 'quadricipiti': 2, 'medio-gluteo': 1, 'addome': 1}, ['squat'], [['kettlebell', 'manubri']], 1, funzionale=True),
 E('affondo_avanti', 'Affondo in avanti', 'forza', ['corpo libero o manubri'], 'carico_ripetizioni',
   ['In piedi, piedi larghezza anche.',
    'Fai un passo lungo in avanti e scendi finché il ginocchio posteriore sfiora il pavimento.',
    'Spingi con il piede anteriore per tornare indietro e alterna.'],
   {'quadricipiti': 3, 'grande-gluteo': 3, 'medio-gluteo': 2, 'adduttori': 1, 'addome': 1}, ['affondo'], [], 1, sollecita=['ginocchia'], funzionale=True),
 E('ponte_distensione', 'Glute bridge con distensione', 'forza', ['manubri'], 'carico_ripetizioni',
   ['Supino, ginocchia piegate, manubri all\'altezza del petto.',
    'Solleva il bacino in ponte e mantienilo alto.',
    'Spingi i manubri verso il soffitto, riportali giù e ripeti restando in ponte.'],
   {'grande-gluteo': 3, 'pettorali': 3, 'tricipite': 2, 'deltoide-anteriore': 2, 'femorali': 1}, ['spinta-orizzontale'], [['manubri'], ['tappetino']], 1),

 # ---------------- spalle ----------------
 E('halo_spinta', 'Halo con spinta', 'core', ['kettlebell, disco o palla medica'], 'carico_ripetizioni',
   ['In piedi, kettlebell tenuto per le corna davanti al petto.',
    'Giralo intorno alla testa vicino al collo, addome contratto e bacino fermo.',
    'Tornato davanti, spingilo sopra la testa; alterna il verso del giro.'],
   {'deltoide-anteriore': 3, 'tricipite': 2, 'obliqui': 2, 'addome': 2, 'trapezio-alto': 1}, ['anti-rotazione'], [['kettlebell', 'palla-medica', 'manubri']], 1),
 E('alzate_frontali', 'Alzate frontali', 'forza', ['manubri, disco o cavo'], 'carico_ripetizioni',
   ['In piedi, manubri davanti alle cosce, gomiti appena piegati.',
    'Solleva le braccia in avanti fino all\'altezza delle spalle.',
    'Scendi lentamente senza slanci del busto.'],
   {'deltoide-anteriore': 3, 'pettorale-alto': 1, 'trapezio-alto': 1}, ['isolamento'], [['manubri', 'cavo', 'palla-medica']], 1),
 E('push_press_kettlebell', 'Push press con kettlebell', 'potenza', ['kettlebell'], 'carico_ripetizioni',
   ['Kettlebell in posizione di rack, piedi larghezza anche.',
    'Piega leggermente le ginocchia e risali con forza.',
    'Usa la spinta delle gambe per portare il kettlebell sopra la testa a braccio teso; cambia braccio.'],
   {'deltoide-anteriore': 3, 'tricipite': 2, 'quadricipiti': 2, 'grande-gluteo': 2, 'addome': 1, 'obliqui': 1}, ['spinta-verticale', 'balistico'], [['kettlebell']], 2, sollecita=['spalle'], funzionale=True),

 # ---------------- piegamenti ----------------
 E('push_up_ginocchia', 'Piegamenti sulle ginocchia', 'forza', ['tappetino'], 'ripetizioni',
   ['Mani poco più larghe delle spalle, ginocchia a terra, corpo in linea dalle ginocchia alla testa.',
    'Scendi con il petto verso il pavimento, gomiti a 45 gradi dal busto.',
    'Spingi per tornare su a braccia tese.'],
   {'pettorali': 3, 'tricipite': 2, 'deltoide-anteriore': 2, 'addome': 1}, ['spinta-orizzontale'], [['tappetino']], 1, sollecita=['polsi']),
 E('push_up_inclinati', 'Piegamenti inclinati', 'forza', ['panca o box'], 'ripetizioni',
   ['Mani sul bordo di panca o box, corpo in linea, piedi a terra.',
    'Scendi portando il petto verso il bordo.',
    'Spingi per tornare a braccia tese.'],
   {'pettorale-basso': 3, 'pettorale-alto': 2, 'tricipite': 2, 'deltoide-anteriore': 2, 'addome': 1}, ['spinta-orizzontale'], [['panca', 'box']], 1, sollecita=['polsi']),
 E('push_up_declinati', 'Piegamenti declinati', 'forza', ['panca o box'], 'ripetizioni',
   ['Piedi su panca o box, mani a terra sotto le spalle.',
    'Scendi con il petto verso il pavimento tenendo il bacino in linea.',
    'Spingi per tornare a braccia tese.'],
   {'pettorale-alto': 3, 'deltoide-anteriore': 3, 'tricipite': 2, 'addome': 2}, ['spinta-orizzontale'], [['panca', 'box']], 2, sollecita=['polsi', 'spalle']),
 E('push_up_diamante', 'Piegamenti presa stretta (diamante)', 'forza', [], 'ripetizioni',
   ['Mani vicine sotto il petto, pollici e indici a formare un diamante.',
    'Scendi tenendo i gomiti vicini al busto.',
    'Spingi per tornare a braccia tese.'],
   {'tricipite': 3, 'pettorali': 2, 'deltoide-anteriore': 2, 'addome': 1}, ['spinta-orizzontale'], [], 2, sollecita=['polsi']),
 E('push_up_larghi', 'Piegamenti presa larga', 'forza', [], 'ripetizioni',
   ['Mani molto più larghe delle spalle, corpo in linea.',
    'Scendi con il petto tra le mani.',
    'Spingi per tornare a braccia tese.'],
   {'pettorali': 3, 'deltoide-anteriore': 2, 'tricipite': 1, 'addome': 1}, ['spinta-orizzontale'], [], 1, sollecita=['polsi', 'spalle']),
 E('pike_push_up', 'Pike push-up', 'forza', [], 'ripetizioni',
   ['Mani a terra, bacino alto e corpo a V rovesciata.',
    'Piega i gomiti portando la testa verso il pavimento davanti alle mani.',
    'Spingi per tornare a braccia tese.'],
   {'deltoide-anteriore': 3, 'tricipite': 2, 'pettorale-alto': 1, 'trapezio-alto': 1}, ['spinta-verticale'], [], 2, sollecita=['polsi', 'spalle']),
 E('push_up_arciere', 'Piegamenti arciere', 'forza', [], 'ripetizioni',
   ['Mani molto larghe, corpo in linea.',
    'Scendi verso una mano piegando quel gomito, l\'altro braccio resta teso.',
    'Spingi per tornare al centro e alterna i lati.'],
   {'pettorali': 3, 'tricipite': 3, 'deltoide-anteriore': 2, 'addome': 2, 'obliqui': 1}, ['spinta-orizzontale'], [], 3, sollecita=['polsi', 'spalle']),
 E('push_up_esplosivi', 'Piegamenti esplosivi', 'potenza', [], 'ripetizioni',
   ['Plank sulle mani, corpo in linea.',
    'Scendi e spingi con forza fino a staccare le mani da terra; se riesci, batti le mani.',
    'Riatterra con i gomiti morbidi e scendi subito nella ripetizione successiva.'],
   {'pettorali': 3, 'tricipite': 2, 'deltoide-anteriore': 2, 'addome': 1}, ['spinta-orizzontale', 'pliometria'], [], 3, sollecita=['polsi', 'spalle'], funzionale=True),
 E('push_up_rotazione', 'Piegamenti con rotazione (T push-up)', 'forza', [], 'ripetizioni',
   ['Plank sulle mani, piedi poco larghi.',
    'Fai un piegamento e risalendo ruota il corpo di lato portando un braccio verso il soffitto.',
    'Torna in plank e alterna il lato.'],
   {'pettorali': 3, 'obliqui': 2, 'deltoide-anteriore': 2, 'tricipite': 2, 'addome': 1}, ['spinta-orizzontale', 'anti-rotazione'], [], 2, sollecita=['polsi'], funzionale=True),
 E('push_up_spiderman', 'Piegamenti spiderman', 'forza', [], 'ripetizioni',
   ['Plank sulle mani, corpo in linea.',
    'Mentre scendi porta un ginocchio di lato verso il gomito.',
    'Spingi per tornare su riportando la gamba indietro e alterna.'],
   {'pettorali': 3, 'obliqui': 2, 'tricipite': 2, 'deltoide-anteriore': 2, 'retto-femorale': 1}, ['spinta-orizzontale', 'anti-rotazione'], [], 2, sollecita=['polsi'], funzionale=True),
 E('hindu_push_up', 'Piegamenti indiani (hindu push-up)', 'forza', [], 'ripetizioni',
   ['Parti dal cane a testa in giù, bacino alto e braccia tese.',
    'Piega i gomiti e scivola in avanti con il petto vicino al pavimento.',
    'Distendi le braccia arrivando al cobra, poi torna indietro con il bacino alto.'],
   {'pettorali': 2, 'deltoide-anteriore': 3, 'tricipite': 2, 'erettori-spinali': 1, 'addome': 1}, ['spinta-orizzontale', 'spinta-verticale'], [], 2, sollecita=['polsi', 'spalle'], funzionale=True),

 # ---------------- braccia ----------------
 E('curl_concentrazione', 'Curl di concentrazione', 'forza', ['manubrio', 'panca'], 'carico_ripetizioni',
   ['Seduto, gomito appoggiato all\'interno della coscia, braccio teso verso il basso.',
    'Porta il manubrio verso la spalla senza muovere il gomito.',
    'Scendi lentamente fino a braccio teso; completa le ripetizioni e cambia braccio.'],
   {'bicipite': 3, 'avambraccio-flessori': 1}, ['isolamento'], [['manubri']], 1),
 E('curl_ez', 'Curl con bilanciere EZ', 'forza', ['bilanciere EZ'], 'carico_ripetizioni',
   ['In piedi, presa sulla parte angolata del bilanciere, gomiti ai fianchi.',
    'Porta il bilanciere verso le spalle senza slanciare il busto.',
    'Scendi lentamente fino a braccia tese.'],
   {'bicipite': 3, 'avambraccio-flessori': 2}, ['isolamento'], [['bilanciere']], 1),
 E('curl_polsi', 'Curl dei polsi', 'forza', ['manubri o bilanciere', 'panca'], 'carico_ripetizioni',
   ['Seduto, avambracci appoggiati sulle cosce, palmi in alto e polsi oltre le ginocchia.',
    'Lascia scendere il peso aprendo le dita, poi chiudi e solleva piegando i polsi.',
    'Solo i polsi si muovono.'],
   {'avambraccio-flessori': 3}, ['isolamento'], [['manubri', 'bilanciere']], 1),
 E('curl_inverso', 'Curl a presa inversa', 'forza', ['bilanciere o manubri'], 'carico_ripetizioni',
   ['In piedi, presa prona (palmi verso il basso), gomiti ai fianchi.',
    'Porta il peso verso le spalle tenendo i polsi dritti.',
    'Scendi lentamente fino a braccia tese.'],
   {'avambraccio-estensori': 3, 'bicipite': 2}, ['isolamento'], [['bilanciere', 'manubri']], 1),

 # ---------------- polpacci ----------------
 E('calf_multipower', 'Calf in piedi al multipower', 'forza', ['multipower', 'rialzo'], 'carico_ripetizioni',
   ['Bilanciere del multipower sulle spalle, avampiedi su un rialzo e talloni liberi.',
    'Sali sulle punte il più in alto possibile, gambe tese.',
    'Scendi lentamente sotto il livello del rialzo.'],
   {'gastrocnemio': 3, 'soleo': 2}, ['polpacci'], [['cavo']], 1),
 E('calf_seduto', 'Calf seduto alla macchina', 'forza', ['macchina calf seduto'], 'carico_ripetizioni',
   ['Seduto, avampiedi sulla pedana, imbottitura sopra le ginocchia.',
    'Sali sulle punte il più in alto possibile.',
    'Scendi lentamente fino al massimo allungamento.'],
   {'soleo': 3, 'gastrocnemio': 1}, ['polpacci'], [['cavo']], 1),

 # ---------------- ginocchio e caviglia ----------------
 E('step_down_eccentrico', 'Step-down eccentrico', 'ricostruzione', ['box o gradino'], 'ripetizioni',
   ['In piedi su un gradino su una gamba, l\'altra libera di lato.',
    'Scendi lentamente piegando la gamba d\'appoggio finché il tallone libero sfiora il pavimento.',
    'Ginocchio in linea con il piede; risali e ripeti, poi cambia gamba.'],
   {'quadricipiti': 3, 'vasto-mediale': 3, 'medio-gluteo': 2, 'grande-gluteo': 1}, ['ginocchio', 'affondo'], [['box']], 1),
 E('camminata_laterale_elastico', 'Camminata laterale con elastico', 'ricostruzione', ['elastico ad anello'], 'ripetizioni',
   ['Elastico sopra le caviglie o le ginocchia, mezzo squat, piedi larghezza anche.',
    'Fai un passo di lato mantenendo l\'elastico in tensione, poi avvicina l\'altro piede senza unirli.',
    'Fai i passi previsti in una direzione e torna nell\'altra.'],
   {'medio-gluteo': 3, 'grande-gluteo': 2, 'quadricipiti': 1}, ['ginocchio', 'locomozione'], [['elastico']], 1),
 E('eversione_caviglia', 'Eversione della caviglia con elastico', 'ricostruzione', ['elastico'], 'ripetizioni',
   ['Seduto con la gamba tesa, elastico attorno all\'avampiede e ancorato verso l\'interno.',
    'Ruota la pianta del piede verso l\'esterno contro l\'elastico, senza muovere il ginocchio.',
    'Torna lentamente; completa le ripetizioni e cambia piede.'],
   {'gastrocnemio-laterale': 2, 'tibiale-anteriore': 1}, ['polpacci'], [['elastico']], 1),

 # ---------------- potenza ----------------
 E('squat_jump', 'Squat jump', 'potenza', [], 'ripetizioni',
   ['Piedi larghezza spalle, scendi in mezzo squat con le braccia indietro.',
    'Salta in alto con forza slanciando le braccia.',
    'Atterra morbido sugli avampiedi e scendi subito nel salto successivo.'],
   {'quadricipiti': 3, 'grande-gluteo': 3, 'polpacci': 2, 'femorali': 1}, ['pliometria', 'squat'], [], 2, impatto=True, sollecita=['ginocchia'], funzionale=True),
 E('step_up_saltato', 'Jump step (step-up saltato)', 'potenza', ['box o step'], 'ripetizioni',
   ['Un piede sul box, l\'altro a terra.',
    'Spingi con la gamba sul box e salta in alto scambiando i piedi in volo.',
    'Atterra con l\'altro piede sul box e ripeti in modo continuo.'],
   {'quadricipiti': 3, 'grande-gluteo': 3, 'polpacci': 2, 'medio-gluteo': 1}, ['pliometria', 'affondo'], [['box']], 2, impatto=True, sollecita=['ginocchia'], funzionale=True),

 # ---------------- funzionali e atletici ----------------
 E('skater_jump', 'Salti laterali (skater)', 'potenza', [], 'ripetizioni',
   ['In equilibrio su una gamba, ginocchio morbido, busto leggermente in avanti.',
    'Spingi di lato e salta atterrando sull\'altra gamba, il piede libero passa dietro.',
    'Ammortizza l\'atterraggio, fermati un istante e salta dall\'altra parte.'],
   {'medio-gluteo': 3, 'grande-gluteo': 3, 'quadricipiti': 2, 'adduttori': 2, 'polpacci': 1}, ['pliometria', 'affondo'], [], 2, impatto=True, sollecita=['ginocchia'], funzionale=True),
 E('salto_lungo', 'Salto in lungo da fermo', 'potenza', [], 'ripetizioni',
   ['Piedi larghezza anche, porta le braccia indietro piegando anche e ginocchia.',
    'Slancia le braccia in avanti e salta più lontano possibile.',
    'Atterra a piedi uniti in mezzo squat, ginocchia in linea con le punte; torna indietro camminando.'],
   {'quadricipiti': 3, 'grande-gluteo': 3, 'femorali': 2, 'polpacci': 2, 'erettori-spinali': 1}, ['pliometria'], [], 2, impatto=True, sollecita=['ginocchia'], funzionale=True),
 E('cossack_squat', 'Cossack squat', 'forza', ['corpo libero o kettlebell'], 'ripetizioni',
   ['Piedi molto larghi, punte leggermente ruotate verso l\'esterno.',
    'Scendi su una gamba fino in fondo; l\'altra resta tesa con la punta del piede verso l\'alto.',
    'Risali e passa dall\'altro lato restando basso, tallone d\'appoggio a terra.'],
   {'adduttori': 3, 'quadricipiti': 2, 'grande-gluteo': 2, 'medio-gluteo': 1, 'femorali': 1}, ['affondo'], [], 2, sollecita=['ginocchia'], funzionale=True),
 E('landmine_rotazione', 'Rotazione al landmine', 'core', ['landmine', 'bilanciere'], 'carico_ripetizioni',
   ['In piedi davanti al landmine, estremità del bilanciere tenuta con due mani a braccia tese davanti al petto.',
    'Porta il bilanciere ad arco verso un fianco ruotando busto e piedi, braccia tese.',
    'Ripassa sopra la testa e scendi verso l\'altro fianco controllando il movimento.'],
   {'obliqui': 3, 'addome': 2, 'deltoide-anteriore': 2, 'grande-gluteo': 1, 'medio-gluteo': 1}, ['rotazione', 'anti-rotazione'], [['landmine']], 2, funzionale=True),
 E('strappo_manubrio', 'Strappo con manubrio', 'potenza', ['manubrio o kettlebell'], 'carico_ripetizioni',
   ['Manubrio a terra tra i piedi, anche indietro, una mano sulla maniglia.',
    'Estendi le anche con forza e tira il manubrio in alto vicino al corpo.',
    'Ruota il gomito sotto e accogli il peso sopra la testa a braccio teso; riportalo giù e cambia braccio.'],
   {'grande-gluteo': 3, 'femorali': 2, 'quadricipiti': 2, 'deltoide-anteriore': 2, 'trapezio-alto': 2, 'tricipite': 1, 'addome': 1}, ['hinge', 'balistico'], [['manubri', 'kettlebell']], 2, sollecita=['spalle'], funzionale=True),
 E('inchworm', 'Inchworm', 'mobilita', [], 'ripetizioni',
   ['In piedi, piegati in avanti e appoggia le mani a terra davanti ai piedi.',
    'Cammina in avanti con le mani fino alla posizione di plank.',
    'Torna indietro con le mani e risali in piedi lentamente.'],
   {'femorali': 2, 'addome': 2, 'deltoide-anteriore': 2, 'pettorali': 1, 'tricipite': 1}, ['mobilita'], [], 1, sollecita=['polsi'], funzionale=True),
 E('step_up_laterale', 'Step-up laterale', 'forza', ['box o step', 'manubri (facoltativi)'], 'carico_ripetizioni',
   ['In piedi di fianco al box, piede vicino sul box.',
    'Sali spingendo con la gamba sul box fino a gamba tesa, l\'altra resta sollevata.',
    'Scendi lentamente con la gamba libera; completa le ripetizioni e cambia lato.'],
   {'quadricipiti': 3, 'medio-gluteo': 3, 'grande-gluteo': 2, 'adduttori': 1}, ['affondo', 'ginocchio'], [['box']], 1, funzionale=True),
 E('navetta', 'Navetta 5-10-5', 'potenza', ['coni'], 'ripetizioni',
   ['Tre coni in linea a 5 metri l\'uno dall\'altro, parti da quello centrale.',
    'Corri 5 metri verso un lato e tocca la linea, poi 10 metri verso l\'altro lato e tocca di nuovo.',
    'Torna al cono centrale; abbassa il baricentro a ogni cambio di direzione.'],
   {'quadricipiti': 2, 'grande-gluteo': 2, 'adduttori': 2, 'medio-gluteo': 2, 'polpacci': 2}, ['locomozione', 'pliometria'], [], 2, impatto=True, sollecita=['ginocchia'], funzionale=True),
]

p = 'src/data/exercises.json'
ex = json.load(open(p))
nuovi_id = {e['id'] for e in NUOVI}
ex = [e for e in ex if e['id'] not in nuovi_id] + NUOVI
json.dump(ex, open(p, 'w'), ensure_ascii=False, indent=2)
print('totale', len(ex), 'nuovi', len(NUOVI))
